export const interests = [
  { value: "all", label: "Show All" },
  { value: "Acting (Drama/Theater)", label: "Acting (Drama/Theater)" },
  { value: "Aerobics", label: "Aerobics" },
  { value: "Astronomy", label: "Astronomy" },
  { value: "Auto Mechanics", label: "Auto Mechanics" },
  { value: "Badminton", label: "Badminton" },
  { value: "Baseball - playing", label: "Baseball - playing" },
  { value: "Baseball - watching", label: "Baseball - watching" },
  { value: "Basketball - playing", label: "Basketball - playing" },
  { value: "Basketball - watching", label: "Basketball - watching" },
  { value: "Bicycling", label: "Bicycling" },
  { value: "Bowling", label: "Bowling" },
  { value: "Boxing", label: "Boxing" },
  { value: "Camping", label: "Camping" },
  { value: "Ceramics/Pottery", label: "Ceramics/Pottery" },
  { value: "Chearleading", label: "Chearleading" },
  { value: "Chess", label: "Chess" },
  { value: "Computers", label: "Computers" },
  { value: "Concerts", label: "Concerts" },
  { value: "Cooking", label: "Cooking" },
  { value: "Crafts", label: "Crafts" },
  { value: "Cricket", label: "Cricket" },
  { value: "Current Events/Politics", label: "Current Events/Politics" },
  { value: "Dance - Ballet", label: "Dance - Ballet" },
  { value: "Dance - Ballroom", label: "Dance - Ballroom" },
  { value: "Dance - Modern/Jazz", label: "Dance - Modern/Jazz" },
  { value: "Field Hockey - playing", label: "Field Hockey - playing" },
  { value: "Field Hockey - watching", label: "Field Hockey - watching" },
  { value: "Fishing", label: "Fishing" },
  {
    value: "Football (Soccer) - playing",
    label: "Football (Soccer) - playing",
  },
  {
    value: "Football (Soccer) - watching",
    label: "Football (Soccer) - watching",
  },
  { value: "Gardening", label: "Gardening" },
  { value: "Golf", label: "Golf" },
  { value: "Gymnastics", label: "Gymnastics" },
  { value: "Handball", label: "Handball" },
  { value: "Hiking", label: "Hiking" },
  { value: "Hockey", label: "Hockey" },
  { value: "Horseback Riding", label: "Horseback Riding" },
  { value: "Hunting", label: "Hunting" },
  { value: "Ice-Skating", label: "Ice-Skating" },
  { value: "Interior Design", label: "Interior Design" },
  { value: "Knitting/Sewing", label: "Knitting/Sewing" },
  { value: "Lacrosse", label: "Lacrosse" },
  {
    value: "Listening to Classical Music",
    label: "Listening to Classical Music",
  },
  { value: "Listening to Pop Music", label: "Listening to Pop Music" },
  { value: "Martial Arts", label: "Martial Arts" },
  { value: "Movies", label: "Movies" },
  { value: "Museums", label: "Museums" },
  { value: "Other", label: "Other" },
  { value: "Paddle Tennis", label: "Paddle Tennis" },
  { value: "Painting/Drawing", label: "Painting/Drawing" },
  { value: "Photography", label: "Photography" },
  { value: "Playing Cards", label: "Playing Cards" },
  {
    value: "Playing Musical Instrument(s)",
    label: "Playing Musical Instrument(s)",
  },
  { value: "Reading", label: "Reading" },
  { value: "Religious Activity", label: "Religious Activity" },
  { value: "Rock Climbing", label: "Rock Climbing" },
  {
    value: "Roller Skating/Roller Blading",
    label: "Roller Skating/Roller Blading",
  },
  { value: "Running/Jogging", label: "Running/Jogging" },
  { value: "Sailing", label: "Sailing" },
  { value: "Scuba Diving", label: "Scuba Diving" },
  { value: "Singing (in choir)", label: "Singing (in choir)" },
  { value: "Skateboarding", label: "Skateboarding" },
  { value: "Skiing", label: "Skiing" },
  { value: "Snowboarding", label: "Snowboarding" },
  { value: "Stamp Collecting", label: "Stamp Collecting" },
  { value: "Swimming", label: "Swimming" },
  { value: "Table Tennis", label: "Table Tennis" },
  { value: "Television", label: "Television" },
  { value: "Tennis", label: "Tennis" },
  { value: "Track and Field", label: "Track and Field" },
  { value: "Travel", label: "Travel" },
  { value: "US Football - playing", label: "US Football - playing" },
  { value: "US Football - watching", label: "US Football - watching" },
  { value: "Video Games", label: "Video Games" },
  { value: "Volleyball", label: "Volleyball" },
  { value: "Weightlifting", label: "Weightlifting" },
  { value: "Wrestling", label: "Wrestling" },
  { value: "Writing", label: "Writing" },
];
